sm-core/src/main/resources/search/product.json
sm-core/src/main/resources/search/product_fr.json
sm-core/src/main/resources/search/settings_product_fr.json

Resolving syntax errors in JSON files.

Fixes #137

---

sm-shop/src/main/java/com/salesmanager/shop/admin/controller/products/ProductController.java

Create similar product is failing. this fix address the issue.
cc: @umeshawasthi

Fixing create similar product error

---

pom.xml
sm-admin/src/main/java/com/salesmanager/admin/initialization/InitStoreData.java
sm-core/src/main/java/com/salesmanager/core/business/repositories/reference/zone/ZoneRepository.java
sm-core/src/main/java/com/salesmanager/core/business/services/reference/init/InitializationDatabaseImpl.java
sm-core/src/main/java/com/salesmanager/core/business/services/reference/zone/ZoneService.java
sm-core/src/main/java/com/salesmanager/core/business/services/reference/zone/ZoneServiceImpl.java
sm-core/src/test/java/com/salesmanager/test/customer/CustomerTest.java
sm-core/src/test/java/com/salesmanager/test/order/InvoiceTest.java
sm-core/src/test/java/com/salesmanager/test/order/OrderTest.java
sm-core/src/test/java/com/salesmanager/test/shipping/ShippingQuoteByWeightTest.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/customers/CustomerController.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/merchant/MerchantStoreController.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/orders/OrderControler.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/shipping/ShippingOriginController.java
sm-shop/src/main/java/com/salesmanager/shop/init/data/InitStoreData.java
sm-shop/src/main/java/com/salesmanager/shop/populator/customer/CustomerPopulator.java

After dropping the unique constraint, zone were populated properly. But the zone look ups started failing due to duplicate zones by zone code. So modified the ZoneRepository to lookup the zone by code and country combination.
Please merge the change
cc: @umeshawasthi , @shopizer-ecommerce

ISSUE-142 : Look up zone by code and country

---

sm-core/src/main/java/com/salesmanager/core/business/repositories/merchant/MerchantRepository.java
sm-core/src/main/java/com/salesmanager/core/business/services/merchant/MerchantStoreServiceImpl.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/merchant/MerchantStoreController.java

These changes should fix the exception during admin login 
Now user can change shop using the store list

Fix for Lazy init exception

---

pom.xml

@shopizer-ecommerce
@umeshawasthi

[enhancement] added Lombook dependency

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/content/ContentApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/content/facade/ContentFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/content/facade/ContentFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/store/facade/StoreFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/store/facade/StoreFacadeImpl.java

[enhancement] Restapi refactoring ContentApi

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/exception/RestErrorHandler.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/category/CategoryApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/content/ContentApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/error/ErrorController.java

fix errorHandling and produces consumer types

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/exception/ConversionRuntimeException.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/exception/RestErrorHandler.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/store/MerchantStoreApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/store/facade/StoreFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/store/facade/StoreFacadeImpl.java

refactored MerchantStoreApi added ConversionRuntimeException

refactored MerchantStoreApi added ConversionRuntimeException

---

README.md

Added shield of stack overflow /last_version/docker link/official site
see preview: https://github.com/DzmitryNev/shopizer/tree/added-shield
see all: https://shields.io/

[enhancement] added shield of stackoverflow & last_version & docker link & official site

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/store/MerchantStoreApi.java

refactored MerchantStoreApi

---

README.md
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerNewsletterApi.java

UnsupportedOperationException it right way in this situation
to avoid sun.reflect.*

replace to UnsupportedOperationException

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerReviewApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/customer/facade/CustomerFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/customer/facade/CustomerFacadeImpl.java

refactored CustomerReviewApi

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/marketplace/MarketPlaceApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/ContactApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/OptinApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/PublicConfigsApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/user/UserApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/marketplace/facade/MarketPlaceFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/marketplace/facade/MarketPlaceFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/optin/OptinConverter.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/optin/OptinFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/optin/OptinFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/optin/OptionConverterImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/system/MerchantConfigurationFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/system/MerchantConfigurationFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/user/facade/UserFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/user/facade/UserFacadeImpl.java

refactored UserApi/MarketPlaceApi/ContactApi/OptinApi/PublicConfigsApi
please test it

refactored UserApi/MarketPlaceApi/ContactApi/OptinApi/PublicConfigsApi

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/references/ReferencesApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/search/SearchApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/country/facade/CountryFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/country/facade/CountryFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/currency/facade/CurrencyFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/currency/facade/CurrencyFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/language/facade/LanguageFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/language/facade/LanguageFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/search/facade/SearchFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/search/facade/SearchFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/zone/facade/ZoneFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/zone/facade/ZoneFacadeImpl.java

refactoring SearchApi & ReferenceApi

---

sm-core/src/main/java/com/salesmanager/core/business/services/catalog/category/CategoryService.java
sm-core/src/main/java/com/salesmanager/core/business/services/catalog/category/CategoryServiceImpl.java
sm-core/src/main/java/com/salesmanager/core/business/services/catalog/product/ProductServiceImpl.java
sm-core/src/test/java/com/salesmanager/test/catalog/ProductTest.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/products/ProductsController.java
sm-shop/src/main/java/com/salesmanager/shop/filter/StoreFilter.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v0/product/ShopProductRESTController.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/category/CategoryApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/category/ShoppingCategoryController.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/category/converter/ReadableCategoryConverter.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/category/facade/CategoryFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/category/facade/CategoryFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/converter/Converter.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/product/facade/ProductFacadeImpl.java

[refactoring] added converter and refactored CategoryApi

---

sm-shop/src/main/java/com/salesmanager/shop/application/LanguageArgumentResolver.java
sm-shop/src/main/java/com/salesmanager/shop/application/MerchantStoreArgumentResolver.java
sm-shop/src/main/java/com/salesmanager/shop/application/ShopApplicationConfiguration.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/category/CategoryApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/content/ContentApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerNewsletterApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerReviewApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderPaymentApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderShippingApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderTotalApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ManufacturerApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductGroupApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductImageApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductRelationshipApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductReviewApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/references/ReferencesApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/search/SearchApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/shoppingCart/ShoppingCartApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/ContactApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/OptinApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/PublicConfigsApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/user/UserApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/content/facade/ContentFacadeImpl.java
sm-shop/src/main/resources/spring/shopizer-controllers.xml

see LanguageArgumentResolver and MerchantStoreArgumentResolver
removed redurant code from restcontrollers
@shopizer-ecommerce

[refactoring] added MerchStore and lang resolvers

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/category/CategoryApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/content/ContentApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerNewsletterApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerReviewApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderPaymentApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderShippingApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderTotalApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ManufacturerApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductGroupApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductImageApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductRelationshipApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductReviewApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/search/SearchApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/shoppingCart/ShoppingCartApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/ContactApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/OptinApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/system/PublicConfigsApi.java

fixed apis for swagger compatibility

---

sm-shop/src/main/java/com/salesmanager/shop/application/ShopApplicationConfiguration.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/AsyncConfig.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/DocumentationConfiguration.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/LanguageArgumentResolver.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/MerchantStoreArgumentResolver.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/ShopApplicationConfiguration.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/ShopizerPropertiesConfig.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/SocialConfig.java
sm-shop/src/main/resources/shopizer-properties.properties
sm-shop/src/main/resources/spring/shopizer-controllers.xml
sm-shop/src/main/resources/spring/shopizer-shop-context.xml

convert xml config to java config

---

sm-shop/src/main/java/com/salesmanager/shop/application/config/AwsLocationImageConfig.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/LocalLocationImageConfig.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/ShopApplicationConfiguration.java
sm-shop/src/main/resources/spring/shopizer-shop-context.xml

moved to java config some profile specific configs

---

pom.xml
sm-core-model/pom.xml
sm-core-modules/pom.xml
sm-core/pom.xml
sm-shop-model/pom.xml
sm-shop/pom.xml

added bill of materials and refactored pom files

---

sm-shop/src/main/webapp/pages/shop/templates/generic/pages/cart.jsp

Change the type of quantity so that the user can only set a positive number for each commodity.

modify the type of quantity in jsp

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/search/SearchApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/search/SearchController.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/search/facade/SearchFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/search/facade/SearchFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/store/facade/content/ContentFacadeImpl.java
sm-shop/src/main/java/com/salesmanager/shop/utils/FilePathUtils.java

refactoring searchService and FilePathUtils

---

sm-core-model/src/main/java/com/salesmanager/core/model/merchant/MerchantStore.java
sm-core/src/main/java/com/salesmanager/core/business/repositories/merchant/MerchantRepository.java
sm-core/src/main/java/com/salesmanager/core/business/services/merchant/MerchantStoreService.java
sm-core/src/main/java/com/salesmanager/core/business/services/merchant/MerchantStoreServiceImpl.java
sm-shop/src/main/java/com/salesmanager/shop/admin/controller/merchant/MerchantStoreController.java

Fix https://github.com/shopizer-ecommerce/shopizer/issues/387.

Add a dedicated query to reduce the amount of unnecessary joined table for MerchantStore

---

README.md

doc: readme file - fix minor typo

---

sm-core-model/src/main/java/com/salesmanager/core/model/system/IntegrationModule.java

Add Index on MODULE_CONFIGURATION.MODULE to Accelerate Query.
See #398

Add index on MODULE_CONFIGURATION.MODULE

---

sm-core-model/src/main/java/com/salesmanager/core/model/user/Group.java

Add Index on SM_GROUP.GROUP_TYPE to Accelerate Query.
See #400

Add index on SM_GROUP.GROUP_TYPE

---

sm-core-model/src/main/java/com/salesmanager/core/model/catalog/product/description/ProductDescription.java

Add Index on PRODUCT_DESCRIPTION.SEF_URL to Accelerate Query.
See #402

Add index on product_description.sef_url

---

sm-shop-model/src/main/java/com/salesmanager/shop/store/controller/product/facade/ProductFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/product/ProductApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/facade/product/ProductFacadeImpl.java

Added REST method for Product by slug (SeUrl)

Added REST method for fetching product by slug/seurl

---

sm-shop-model/src/main/java/com/salesmanager/shop/model/system/Configs.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/system/MerchantConfigurationFacadeImpl.java

Just exposing a bit more configuration info through the API .

Exposing more Store Configurations at config Api v1

---

sm-core/src/main/java/com/salesmanager/core/business/services/reference/language/LanguageServiceImpl.java
sm-shop/src/main/java/com/salesmanager/shop/application/config/ShopApplicationConfiguration.java

This little change, allows for admin site to appear in default locale, otherwise it had to be selected with every login.

Takes default locale for sessions

---

sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/customer/CustomerApi.java

This allows   clients to get their profile, and not only   Administrators to get Client profile

Adding  auth/customer/profile mapping for CustomerApi to get profile.

---

README.md

Adds to the README.md configuration information required to run the project on IntelliJ

Add information to execute the project in Intellij

---

sm-shop/src/main/java/com/salesmanager/shop/application/config/ShopApplicationConfiguration.java
sm-shop/src/main/java/com/salesmanager/shop/model/shop/PageInformation.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/product/ShopProductController.java
sm-shop/src/main/java/com/salesmanager/shop/utils/FilePathUtils.java
sm-shop/src/main/webapp/pages/shop/templates/december/catalogLayout.jsp

Enables social card for products (facebook, whatsapp, twitter):

Adds meta tags information for product social media cards

---

sm-shop/src/main/java/com/salesmanager/shop/store/facade/product/ProductTypeFacadeImpl.java

Fix of bug which returned 0 every time

Fetch and return saved Entity id

---

sm-shop/src/main/java/com/salesmanager/shop/store/controller/order/ShoppingOrderController.java

Issue Fixed:
https://github.com/shopizer-ecommerce/shopizer/issues/587

Fixed issue 587

---

sm-shop/src/main/webapp/pages/shop/templates/december/sections/header.jsp

Fixed issue 418:
https://github.com/shopizer-ecommerce/shopizer/issues/418

Fixed issue 418

---

sm-core/src/main/java/com/salesmanager/core/business/modules/cms/product/ProductFileManagerImpl.java
sm-core/src/main/java/com/salesmanager/core/business/services/catalog/product/image/ProductImageServiceImpl.java
sm-core/src/main/java/com/salesmanager/core/business/services/order/OrderServiceImpl.java
sm-core/src/main/java/com/salesmanager/core/business/utils/ProductImageSizeUtils.java
sm-shop-model/src/main/java/com/salesmanager/shop/model/catalog/product/LightPersistableProduct.java
sm-shop/src/main/java/com/salesmanager/shop/populator/catalog/PersistableProductPopulator.java
sm-shop/src/main/java/com/salesmanager/shop/populator/catalog/ReadableProductPopulator.java
sm-shop/src/main/java/com/salesmanager/shop/store/api/v1/order/OrderApi.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/order/facade/OrderFacade.java
sm-shop/src/main/java/com/salesmanager/shop/store/controller/order/facade/OrderFacadeImpl.java

Run in 2.16 and not able to test in master due problems with startup out of the box
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tilesConfigurer' defined in class path resource [com/salesmanager/shop/application/config/ShopApplicationConfiguration.class]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: No URL for ServletContext resource [/WEB-INF/tiles/tiles-admin.xml]

- Added possibility to add and retreive external product images via ProductApi

---

sm-shop-model/src/main/java/com/salesmanager/shop/store/controller/user/facade/UserFacade.java

- I fixed the names of the parameters store and groupNames from the Javadoce. 
- I removed the @param storeCode from the Javadoc because the method changePassword doesn't have this parameter.

Fix Javadoc's @param

---

sm-core/src/main/java/com/salesmanager/core/business/utils/DataUtils.java
sm-core/src/test/java/com/salesmanager/test/business/utils/DataUtilsTest.java

This PR updates deprecated code references in DataUtils class and also creates the junit tests cases for all methods in DataUtils.

update deprecated code and add junit

---

pom.xml

Correct web name typo in the main pom file

---

sm-core/src/main/java/com/salesmanager/core/business/services/reference/country/CountryServiceImpl.java

Filter out duplicate countries

duplicate-countries-in-the-list
